apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: ceph-osd
  labels:
    name: ceph-osd
  namespace: ceph
spec:
  template:
    metadata:
      labels:
        name: ceph-osd
    spec:
      hostNetwork: true
      nodeSelector:
        cdx/ceph-osd: "true"
      volumes:
        - name: docker
          hostPath:
            path: /run/torcx/unpack/docker/bin/docker
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
        - name: hostlib
          hostPath:
            path: /run/torcx/unpack/docker/lib
        - name: ceph-conf-combined
          secret:
            secretName: ceph-conf-combined
        - name: ceph-bootstrap-osd-keyring
          secret:
            secretName: ceph-bootstrap-osd-keyring
        - name: ceph-bootstrap-mds-keyring
          secret:
            secretName: ceph-bootstrap-mds-keyring
        - name: ceph-bootstrap-rgw-keyring
          secret:
            secretName: ceph-bootstrap-rgw-keyring
        - name: ceph-bootstrap-rbd-keyring
          secret:
            secretName: ceph-bootstrap-rbd-keyring
        - name: ceph-conf-yaml
          secret:
            secretName: ceph-conf-yaml
        - name: ceph-dns-conf
          secret:
            secretName: ceph-dns-conf
        - name: dev
          hostPath:
            path: /dev/
      containers:
        - name: ceph-osd-pod
          image: cdxvirt/ceph-daemon:daemon-13.2.1-1
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          args: ["cdx_osd"]
          volumeMounts:
            - name: docker
              mountPath: /bin/docker
            - name: docker-sock
              mountPath: /var/run/docker.sock
            - name: hostlib
              mountPath: /host/lib
            - name: ceph-conf-combined
              mountPath: /etc/ceph/
            - name: ceph-bootstrap-osd-keyring
              mountPath: /var/lib/ceph/bootstrap-osd
            - name: ceph-bootstrap-mds-keyring
              mountPath: /var/lib/ceph/bootstrap-mds
            - name: ceph-bootstrap-rgw-keyring
              mountPath: /var/lib/ceph/bootstrap-rgw
            - name: ceph-bootstrap-rbd-keyring
              mountPath: /var/lib/ceph/bootstrap-rbd
            - name: ceph-conf-yaml
              mountPath: /ceph-conf-yaml
            - name: ceph-dns-conf
              mountPath: /etc/resolv.conf
              subPath: resolv.conf
            - name: dev
              mountPath: /dev
