apiVersion: batch/v1
kind: Job
metadata:
  name: ceph-initial-job
  namespace: ceph
  labels:
    cdxvirt/cluster-service: "true"
spec:
  template:
    metadata:
      name: ceph-initial-job
    spec:
      containers:
      - name: create-k8s-secrets
        image: cdxvirt/ceph-daemon:daemon-13.2.1-1
        imagePullPolicy: IfNotPresent
        command: ["/cdx/ceph-init.sh"]
        env:
          - name: "CEPH_PUBLIC_NETWORK"
            valueFrom:
              configMapKeyRef:
                name: ceph-env
                key: CEPH_PUBLIC_NETWORK
          - name: "CEPH_CLUSTER_NETWORK"
            valueFrom:
              configMapKeyRef:
                name: ceph-env
                key: CEPH_CLUSTER_NETWORK
      restartPolicy: Never
