apiVersion: v1
kind: Service
metadata:
  name: ceph-mon
  namespace: ceph
  labels:
    name: ceph-mon
    cdxvirt/cluster-service: "true"
spec:
  clusterIP: None
  ports:
  - port: 6789
    protocol: TCP
