kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: ceph-mds
  namespace: ceph
spec:
  template:
    metadata:
      labels:
        name: ceph-mds
    spec:
      hostNetwork: true
      nodeSelector:
        cdx/ceph-mds: "true"
      volumes:
        - name: localtime
          hostPath:
            path: /etc/localtime
      containers:
        - name: ceph-mds-pod
          image: cdxvirt/ceph-daemon:latest
          imagePullPolicy: IfNotPresent
          args: ["mds"]
          env:
            - name: "CDX_ENV"
              value: "true"
#            - name: "DEBUG"
#              value: "verbose"
          volumeMounts:
            - name: localtime
              mountPath: /etc/localtime
