# CEPH DAEMON IMAGE
# CEPH VERSION: Luminous
# CEPH VERSION DETAIL: 12.x.x

FROM cdxvirt/ceph-base:base-12.1.4
MAINTAINER CDXVIRT

# cdxvirt packages
ARG CDXVIRT_PKG="curl grepcidr inotify-tools vim kmod jq mdadm lvm2 net-tools"

# install packages for cdxvirt
RUN DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y $CDXVIRT_PKG && \
    apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Add s3cfg file
ADD s3cfg /root/.s3cfg

# Add bootstrap script, ceph defaults key/values for KV store
ADD *.sh ceph.defaults check_zombie_mons.py ./osd_scenarios/* entrypoint.sh.in disabled_scenario /

# Modify the entrypoint
RUN bash "/generate_entrypoint.sh" && \
  rm -f /generate_entrypoint.sh && \
  bash -n /*.sh

# Add templates for confd
ADD ./confd/templates/* /etc/confd/templates/
ADD ./confd/conf.d/* /etc/confd/conf.d/

# Add cdxvirt scripts
ADD cdx /cdx
RUN mv /cdx/ceph-api /usr/local/bin/ceph-api

# Execute the entrypoint
WORKDIR /
ENTRYPOINT ["/entrypoint.sh"]
