FROM @UBUNTU_BASE_IMG@
MAINTAINER VSDX

RUN DEBIAN_FRONTEND=noninteractive apt-get update && \
      apt-get install -y -f && \
      apt-get install -y --no-install-recommends --force-yes \
      iproute grepcidr vim supervisor jq && \
      apt-get clean && \
      rm -rf /var/lib/apt/lists/* \
             /var/cache/debconf/* \
             /var/log/apt/ \
             /var/log/dpkg.log

# Add s3cfg file
ADD s3cfg /root/.s3cfg

# Add templates for confd
ADD ./confd/templates/* /etc/confd/templates/
ADD ./confd/conf.d/* /etc/confd/conf.d/

# Add bootstrap script, ceph defaults key/values for KV store
ADD *.sh ceph.defaults check_zombie_mons.py ./osd_scenarios/* entrypoint.sh.in disabled_scenario /

# Add cdxvirt scripts
ADD cdx /cdx

# Modify the entrypoint
RUN bash "/generate_entrypoint.sh" && \
  rm -f /generate_entrypoint.sh && \
  bash -n /*.sh

# Execute the entrypoint
WORKDIR /
ENTRYPOINT ["/entrypoint.sh"]
